version: "3.9"

services:
  api:
    command: bash -c 'sleep 10 && echo "Starting API..." && while !</dev/tcp/db/5432; do sleep 1; done; yarn dev'
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./.env
