version: "3.9"
services:
  api_express:
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn dev'
    container_name: api_express
    image: node:16-alpine
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    container_name: db
    image: postgres:12-alpine
    ports:
      - 5431:5432
    env_file:
      - ./.env
